### ISSUE TITLE
Virus total detections

### ISSUE THREAD

**Issue by comeollas** [pinksheetscrypto/covid-blockchain#10]
Hi, i want to try this fork but i tried to Analise the windows files in virustotal website i uploaded and virus total have some Trojan detection (maybe false positives).

For me it's sufficient for avoid using Covid coin i recommend to solve this issue.

**Comment by pinksheetscrypto** [comment]
Sorry for the late response.  Almost all of the Chia forks are being reported as having Trojan.  I am looking into submitting the app for approval. Luckily with the code on Github for everyone to see it is pretty hard to hide something malevolent.

**Comment by pinksheetscrypto** [comment]
![image](https://user-images.githubusercontent.com/87739022/129116385-6a1d3f4c-7049-4a4c-b88f-1273850fbc4d.png)
