### ISSUE TITLE
[BUG] Covid wirting 1 TB of debug log every day

### ISSUE THREAD

**Issue by JariNestel** [pinksheetscrypto/covid-blockchain#27]
**Describe the bug**
Covid writes 1 TB of debug log every day

**To Reproduce**

1. install
2. start
3. enter wallet

**Expected behavior**
Less log

**Desktop**
- OS: Windows 10
- OS Version/Flavor: 10.0.19043 Build 19043
- CPU: AMD Ryzen 5 3600

**Additional context**
I've been getting into Taco in combination with multiple other forks, most seem to have this problem, I've checked if there are port collisions, there aren't.
Others are: Chaingreen, Chia, Covid, DogeChia, Flax, Silicon, Taco

**Comment by pinksheetscrypto** [comment]
That is very odd.  In the config.yaml file did you leave the default log level of INFO?  With INFO it appears to be writing a 20 meg file every 2-3 days.  If you change it to WARNING it will probably take a fraction of that.  Or perhaps you are saying you have changed it to DEBUG?

**Comment by JariNestel** [comment]
I've looked into the config.yaml
```yaml
(...)
farmer:
  (...)
  logging: &id001
    log_filename: log/debug.log
    log_level: INFO
    (...)
  (...)
(...)
```
this is the only occurrence of the string "log/debug.log" - I've now successfully managed to break my installation, by installing the "Optional: Update to Chia 1.2.3 code and some UI enhancements" v1.2.3.1 - this might be a windows problem, so I'll have a look at a fresh start once the PC finished plotting.

**Comment by JariNestel** [comment]
After Upgrading to Version 1.2.3.1 and Restarting Windows the log is now just the normal info averaging out at ~1 MB/hour, seems like 1.2.3 already contains a magical fix or it was just Windows failing. Thanks for your help.
