### ISSUE TITLE
What is the plan for COVID?

### ISSUE THREAD

**Issue by yjiangnan** [pinksheetscrypto/covid-blockchain#31]
It is currently unclear where COVID is heading. There is no description available. What is the plan here?

**Comment by pinksheetscrypto** [comment]
To be honest, I have not been able to spend as much time on covid as I would like to.  Tonight I am pushing out the Chia 1.2.9 changes.  After that I am going to focus on releasing a crypto exchange.  I hope to get back to covid late November.  I should have more info then.
