### ISSUE TITLE
GUI installation error in Ubuntu 20.04[BUG]

### ISSUE THREAD

**Issue by panosvo** [pinksheetscrypto/covid-blockchain#7]
**Describe the bug**
<When installing through CLI in ubuntu 20.04, after running the command "sh install-gui.sh"  I am getting the following error: 

"ERROR in ./src/components/icons/index.ts 1:0-43
Module not found: Error: Can't resolve './Covid' in '/home/chia1/covid-blockchain/covid-blockchain-gui/src/components/icons'
 @ ./src/components/dashboard/DashboardSideBar.tsx 6:0-142 28:43-51 37:43-53 45:43-51 53:43-51 61:43-51 69:43-51
 @ ./src/components/dashboard/Dashboard.tsx 16:0-50 78:89-105
 @ ./src/components/app/AppRouter.tsx 9:0-47 55:38-47
 @ ./src/components/app/App.tsx 25:0-36 82:138-147
 @ ./src/index.tsx 5:0-39 6:50-53"

 -->

After this, the GUI starts but there is no option to create a wallet or install the existing 24 words" 
**To Reproduce**
I have tried this on two different machines, with e same error!

**Comment by panosvo** [comment]
Bug fixed, thanks 6708b50

**Comment by pinksheetscrypto** [comment]
Sorry for the delay.  I actually was going to test this first first but had to install a GUI version of Ubuntu and then got stuck on the day job.
